In [597]:
import numpy as np
import matplotlib.pyplot as plt
import time

In [598]:
def fast_F(matrix_index,X):
    
    result = np.zeros([N,N], dtype = complex)
    
    for i in np.arange(9):
        
        if i != matrix_index - 1:
            temp_result = np.zeros([N,N], dtype = complex)
            
            for n in np.arange(N):
                for m in np.arange(N):
                    
                    if m >= n:
                        sum1, sum2, sum3 = 0,0,0
                        
                        for a in np.arange(N):
                            for b in np.arange(N):

                                sum1 += X[i][n][a] * X[matrix_index - 1][a][b] * X[i][b][m]
                                sum2 += X[i][n][a] * X[i][a][b] * X[matrix_index - 1][b][m]
                                sum3 += X[matrix_index - 1][n][a] * X[i][a][b] * X[i][b][m]
                                
                        temp_result[n][m] = 2*sum1 - sum2 - sum3
                
                    else:
                        temp_result[n][m] = np.conjugate(temp_result[m][n])
                    
                    #print(temp_result)
                    
            result += temp_result
            
        else:
            continue
            
    return result

In [599]:
def fast_F_2(k,X):
    #Fs = np.zeros([9,N,N], dtype = complex)
    result = np.zeros([N,N], dtype = complex)
    
    for i in np.arange(9):
        if i != (k - 1):
            temp = np.dot(np.dot(X[i],X[i]),X[k-1])
            #Fs[i] = 2*np.dot(np.dot(X[i],X[k-1]),X[i]) - temp - np.conjugate(temp.T)
            result += 2*np.dot(np.dot(X[i],X[k-1]),X[i]) - temp - np.conjugate(temp.T)
    
    return result # np.sum(Fs, axis = 0)

In [600]:
def commutator(A,B):
    return np.dot(A,B) - np.dot(B,A)

def F(Xi,X):
    
    F = np.zeros([N,N], dtype = complex)
    for j in np.arange(9):
        F += commutator(X[j],commutator(Xi,X[j]))
    return F

def H(X,V):
    
    sum1 = 0
    for k in np.arange(9):
        sum1 += np.dot(V[k],V[k]).trace()
        
        
    sum2 = np.zeros([N,N], dtype = complex)
    for i in np.arange(9):
        for j in np.arange(9):
            if j == i:
                continue
            sum2 += np.dot(commutator(X[i],X[j]),commutator(X[i],X[j]))
    
    T = 1/(2*g**2) * sum1
    U = -1/(4*g**2) * sum2.trace()
    return np.abs(T + U)

In [593]:
X = np.array([X1,X2,X3,X4,X5,X6,X7,X8,X9])

In [601]:
start = time.time()
for i in np.arange(100000):
    fast_F_2(1,X)

time.time() - start

11.303452730178833

In [596]:
start = time.time()
for i in np.arange(100000):
    F(X1,X)

time.time() - start

8.288036346435547

In [576]:
fast_F_2(1,X)

array([[  6.75505947-1.30104261e-18j, -21.89941017+3.09246340e+01j],
       [-21.89941017-3.09246340e+01j,  -6.75505947-1.30104261e-18j]])

In [575]:
F(X1,X)

array([[  6.75505947+1.56558794e-16j, -21.89941017+3.09246340e+01j],
       [-21.89941017-3.09246340e+01j,  -6.75505947+1.56558794e-16j]])

In [591]:
# Creating random, complex, traceless, hermitian matrices X 

N = 5

X1 = np.zeros([N,N],dtype = complex)
X2 = np.zeros([N,N],dtype = complex)
X3 = np.zeros([N,N],dtype = complex)
X4 = np.zeros([N,N],dtype = complex)
X5 = np.zeros([N,N],dtype = complex)
X6 = np.zeros([N,N],dtype = complex)
X7 = np.zeros([N,N],dtype = complex)
X8 = np.zeros([N,N],dtype = complex)
X9 = np.zeros([N,N],dtype = complex)

for i in np.arange(N):
    for j in np.arange(N):
        
        if (i==j) & (i != N-1):
            X1[i][j] = complex(np.random.normal(0,1),0)
            X2[i][j] = complex(np.random.normal(0,1),0)
            X3[i][j] = complex(np.random.normal(0,1),0)
            X4[i][j] = complex(np.random.normal(0,1),0)
            X5[i][j] = complex(np.random.normal(0,1),0)
            X6[i][j] = complex(np.random.normal(0,1),0)
            X7[i][j] = complex(np.random.normal(0,1),0)
            X8[i][j] = complex(np.random.normal(0,1),0)
            X9[i][j] = complex(np.random.normal(0,1),0)
            
        elif (i != j):
            X1[i][j] = complex(np.random.normal(0,1),np.random.normal(0,1))
            X1[j][i] = X1[i][j].conjugate()
            X2[i][j] = complex(np.random.normal(0,1),np.random.normal(0,1))
            X2[j][i] = X2[i][j].conjugate()
            X3[i][j] = complex(np.random.normal(0,1),np.random.normal(0,1))
            X3[j][i] = X3[i][j].conjugate()
            X4[i][j] = complex(np.random.normal(0,1),np.random.normal(0,1))
            X4[j][i] = X4[i][j].conjugate()
            X5[i][j] = complex(np.random.normal(0,1),np.random.normal(0,1))
            X5[j][i] = X5[i][j].conjugate()
            X6[i][j] = complex(np.random.normal(0,1),np.random.normal(0,1))
            X6[j][i] = X6[i][j].conjugate()
            X7[i][j] = complex(np.random.normal(0,1),np.random.normal(0,1))
            X7[j][i] = X7[i][j].conjugate()
            X8[i][j] = complex(np.random.normal(0,1),np.random.normal(0,1))
            X8[j][i] = X8[i][j].conjugate()
            X9[i][j] = complex(np.random.normal(0,1),np.random.normal(0,1))
            X9[j][i] = X9[i][j].conjugate()
            
        else:
            current_sum_1 = complex(0,0)
            current_sum_2 = complex(0,0)
            current_sum_3 = complex(0,0)
            current_sum_4 = complex(0,0)
            current_sum_5 = complex(0,0)
            current_sum_6 = complex(0,0)
            current_sum_7 = complex(0,0)
            current_sum_8 = complex(0,0)
            current_sum_9 = complex(0,0)
            
            for k in np.arange(N-1):
                current_sum_1 += X1[k][k]
                current_sum_2 += X2[k][k]
                current_sum_3 += X3[k][k]
                current_sum_4 += X4[k][k]
                current_sum_5 += X5[k][k]
                current_sum_6 += X6[k][k]
                current_sum_7 += X7[k][k]
                current_sum_8 += X8[k][k]
                current_sum_9 += X9[k][k]
                
            X1[i][j] = - current_sum_1
            X2[i][j] = - current_sum_2
            X3[i][j] = - current_sum_3
            X4[i][j] = - current_sum_4
            X5[i][j] = - current_sum_5
            X6[i][j] = - current_sum_6
            X7[i][j] = - current_sum_7
            X8[i][j] = - current_sum_8
            X9[i][j] = - current_sum_9

V1,V2,V3,V4,V5,V6,V7,V8,V9 = np.zeros([9,N,N], dtype = complex)
X1R,X2R,X3R,X4R,X5R,X6R,X7R,X8R,X9R = X1,X2,X3,X4,X5,X6,X7,X8,X9

In [592]:
X1,X2,X3,X4,X5,X6,X7,X8,X9 = X1R,X2R,X3R,X4R,X5R,X6R,X7R,X8R,X9R
V1,V2,V3,V4,V5,V6,V7,V8,V9 = np.zeros([9,N,N], dtype = complex)

In [579]:
X1 # X1 starts at this value

array([[-0.49364114+0.j        ,  0.45177717-0.44828463j],
       [ 0.45177717+0.44828463j,  0.49364114-0.j        ]])

In [580]:
start = time.time()
g = 5
dt = 1e-4

X = np.array([X1,X2,X3,X4,X5,X6,X7,X8,X9], dtype = complex)
V = np.array([V1,V2,V3,V4,V5,V6,V7,V8,V9], dtype = complex)

for i in np.arange(10000):
    
    X1_n = X1 + V1*dt + F(X1,X)*dt**2/2
    X2_n = X2 + V2*dt + F(X2,X)*dt**2/2
    X3_n = X3 + V3*dt + F(X3,X)*dt**2/2
    X4_n = X4 + V4*dt + F(X4,X)*dt**2/2
    X5_n = X5 + V5*dt + F(X5,X)*dt**2/2
    X6_n = X6 + V6*dt + F(X6,X)*dt**2/2
    X7_n = X7 + V7*dt + F(X7,X)*dt**2/2
    X8_n = X8 + V8*dt + F(X8,X)*dt**2/2
    X9_n = X9 + V9*dt + F(X9,X)*dt**2/2
    
    X_n = np.array([X1_n,X2_n,X3_n,X4_n,X5_n,X6_n,X7_n,X8_n,X9_n])
    
    V1 = V1 + (F(X1,X) + F(X1_n,X_n))*dt/2
    V2 = V2 + (F(X2,X) + F(X2_n,X_n))*dt/2
    V3 = V3 + (F(X3,X) + F(X3_n,X_n))*dt/2
    V4 = V4 + (F(X4,X) + F(X4_n,X_n))*dt/2
    V5 = V5 + (F(X5,X) + F(X5_n,X_n))*dt/2
    V6 = V6 + (F(X6,X) + F(X6_n,X_n))*dt/2
    V7 = V7 + (F(X7,X) + F(X7_n,X_n))*dt/2
    V8 = V8 + (F(X8,X) + F(X8_n,X_n))*dt/2
    V9 = V9 + (F(X9,X) + F(X9_n,X_n))*dt/2
    
    X1, X2, X3, X4, X5, X6, X7, X8, X9 = X1_n, X2_n, X3_n, X4_n, X5_n, X6_n, X7_n, X8_n, X9_n
    X = np.array([X1,X2,X3,X4,X5,X6,X7,X8,X9])
    V = np.array([V1,V2,V3,V4,V5,V6,V7,V8,V9])

print(time.time() - start)

21.956254243850708


In [581]:
X1

array([[ 0.31064108-4.82320380e-20j,  0.20382644+5.29269066e-01j],
       [ 0.20382644-5.29269066e-01j, -0.31064108-4.82320380e-20j]])

In [582]:
start = time.time()
g = 5
dt = 1e-4

X = np.array([X1,X2,X3,X4,X5,X6,X7,X8,X9], dtype = complex)
V = np.array([V1,V2,V3,V4,V5,V6,V7,V8,V9], dtype = complex)

for i in np.arange(10000):
    
    X1_n = X1 + V1*dt + fast_F_2(1,X)*dt**2/2
    X2_n = X2 + V2*dt + fast_F_2(2,X)*dt**2/2
    X3_n = X3 + V3*dt + fast_F_2(3,X)*dt**2/2
    X4_n = X4 + V4*dt + fast_F_2(4,X)*dt**2/2
    X5_n = X5 + V5*dt + fast_F_2(5,X)*dt**2/2
    X6_n = X6 + V6*dt + fast_F_2(6,X)*dt**2/2
    X7_n = X7 + V7*dt + fast_F_2(7,X)*dt**2/2
    X8_n = X8 + V8*dt + fast_F_2(8,X)*dt**2/2
    X9_n = X9 + V9*dt + fast_F_2(9,X)*dt**2/2
    
    X_n = np.array([X1_n,X2_n,X3_n,X4_n,X5_n,X6_n,X7_n,X8_n,X9_n])
    
    V1 = V1 + (fast_F_2(1,X) + fast_F_2(1,X_n))*dt/2
    V2 = V2 + (fast_F_2(2,X) + fast_F_2(2,X_n))*dt/2
    V3 = V3 + (fast_F_2(3,X) + fast_F_2(3,X_n))*dt/2
    V4 = V4 + (fast_F_2(4,X) + fast_F_2(4,X_n))*dt/2
    V5 = V5 + (fast_F_2(5,X) + fast_F_2(5,X_n))*dt/2
    V6 = V6 + (fast_F_2(6,X) + fast_F_2(6,X_n))*dt/2
    V7 = V7 + (fast_F_2(7,X) + fast_F_2(7,X_n))*dt/2
    V8 = V8 + (fast_F_2(8,X) + fast_F_2(8,X_n))*dt/2
    V9 = V9 + (fast_F_2(9,X) + fast_F_2(9,X_n))*dt/2
    
    X1, X2, X3, X4, X5, X6, X7, X8, X9 = X1_n, X2_n, X3_n, X4_n, X5_n, X6_n, X7_n, X8_n, X9_n
    X = np.array([X1,X2,X3,X4,X5,X6,X7,X8,X9])
    V = np.array([V1,V2,V3,V4,V5,V6,V7,V8,V9])

print(time.time() - start)

27.140979766845703


In [583]:
X1

array([[-0.0444925 -9.35598031e-16j,  0.59396428-4.06476359e-01j],
       [ 0.59396428+4.06476359e-01j,  0.0444925 -9.35598031e-16j]])